<?php
// echo "<form action=\"http://localhost/multas/public/index.php/multa/list\" method=\"post\">";
echo "<form action=\"" . DIRURL . "/multa/" . $data["id"] . "\" method=\"post\">";
echo "<label for=\"id\">IdMulta";
echo "<input type=\"text\" name=\"id\" placeholder=\"id\" value=\"" . $data["id"] . "\" readonly>";
echo "</label>";
echo "<br>";
echo "<label for=\"id_conductor\">Conductor";
echo "<input type=\"text\" name=\"id_conductor\" placeholder=\"id_conductor\" value=\"" . $data["id_conductor"] . "\" readonly>";
echo "</label>";
echo "<br>";
echo "<label for=\"matricula\">Matrícula";
echo "<input type=\"text\" name=\"matricula\" placeholder=\"matricula\" value=\"" . $data["matricula"] . "\" readonly>";
echo "</label>";
echo "<br>";
echo "<label for=\"id_tipo_sanciones\">Tipo de infraccion";
echo "<input type=\"text\" name=\"id_tipo_sanciones\" placeholder=\"id_tipo_sanciones\" value=\"" . $data["id_tipo_sanciones"] . "\" readonly>";
echo "</label>";
echo "<br>";
echo "<label for=\"descripcion\">Descripción";
echo "<input type=\"text\" name=\"descripcion\" placeholder=\"descripcion\" value=\"" . $data["descripcion"] . "\" readonly>";
echo "</label>";
echo "<br>";
echo "<label for=\"fecha\">Fecha";
echo "<input type=\"text\" name=\"fecha\" placeholder=\"fecha\" value=\"" . $data["fecha"] . "\" readonly>";
echo "</label>";
echo "<br>";
echo "<label for=\"importe\">Importe";
echo "<input type=\"text\" name=\"importe\" placeholder=\"importe\" value=\"" . $data["importe"] . "\" readonly>";
echo "</label>";
echo "<br>";
echo "<label for=\"descuento\">Decuento";
echo "<input type=\"text\" name=\"descuento\" placeholder=\"descuento\" value=\"" . $data["descuento"] . "\" readonly>";
echo "</label>";
echo "<br>";
echo "<input type=\"submit\" name=\"pagar\" value=\"pagar\">";
echo "</form>";
